#!groovy

properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')),
    pipelineTriggers([])
])

pipeline {
    agent { label 'devel9-head' }
    stages {
        stage('Build Node Image') {
            steps {
                script {
                    sh """
                        docker build -t $DOCKER_NAME --pull --no-cache -f pipelines/build-dk5-image/Dockerfile .
                        docker tag $DOCKER_NAME $DOCKER_NAME_LATEST
                    """
                }
            }
        }
        stage('Push to Artifactory') {
            when { branch "master" }
            steps {
                script {
                    if (currentBuild.resultIsBetterOrEqualTo('SUCCESS')) {
                        docker.image("${DOCKER_NAME}").push("${BUILD_NUMBER}")
                        docker.image("${DOCKER_NAME_LATEST}").push("latest")
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                sh """
                    docker image rm $DOCKER_NAME
                """
            }
        }
    }
}
