language: node_js
sudo: true
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test
  - TEST_SUITE=test:integration
services:
  - elasticsearch
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.2.deb && sudo service elasticsearch restart
script: npm run $TEST_SUITE
addons:
  sauce_connect: true
