language: node_js
sudo: true
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - TEST_SUITE=test
services:
  - elasticsearch
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/5.2.1/elasticsearch-5.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.2.1.deb && sudo service elasticsearch restart
before_script:
  - sleep 10
script: npm run $TEST_SUITE
addons:
  sauce_connect: true
