#!groovy​
@Library('pu-deploy')_

def DOCKER_REPO = "docker-fbiscrum.artifacts.dbccloud.dk"

properties([
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')),
        pipelineTriggers([]),
        disableConcurrentBuilds()
])

def FILE = "dk5_total.iso2709"

pipeline {
    agent {
        docker {
            image "${DOCKER_REPO}/dbc-libv3-env:latest"
            label 'devel10-head'
        }
    }
    triggers {
        cron("H 5 * * *")
    }
    environment {
        ARTIFACTORY_FE_GENERIC = "https://artifactory.dbccloud.dk/artifactory/fe-generic/dk5/"
        ARTIFACTORY_LOGIN = credentials("artifactory_login")
        TANTER_LOGIN = credentials("tanter_login")
    }

    stages {
        stage('Dump DK5') {
            steps {
                script {
                    sh """
                        pwd
                        ls -la /root
                        /root/.rrdump/bin/rrdump.sh -f ISO -a 190007 -u http://rawrepo-record-service.cisterne.svc.cloud.dbc.dk -o ${FILE}
                    """
                }
            }
        }
        stage('Send file to Artifactory') {
            when {
                branch "master"
            }
            steps {
                script {
                    sh "echo archive ${FILE}"
                    archiveArtifacts "${FILE}"
                    sh "echo push to ${ARTIFACTORY_FE_GENERIC}${FILE}"
                    sh "curl -k -u ${ARTIFACTORY_LOGIN} -T ${FILE} ${ARTIFACTORY_FE_GENERIC}${FILE}"
                }
            }
        }
    }
    post {
        failure {
            when {branch "master"} {
                script {
                    slackSend(channel: 'fe-drift',
                            color: 'warning',
                            message: "${env.JOB_NAME} #${env.BUILD_NUMBER} failed and needs attention: ${env.BUILD_URL}",
                            tokenCredentialId: 'slack-global-integration-token')
                }
            }
        }
        success {
            script {
                if ("${env.BRANCH_NAME}" == 'master') {
                    slackSend(channel: 'fe-drift',
                            color: 'good',
                            message: "${env.JOB_NAME} #${env.BUILD_NUMBER} completed, and pushed ${FILE} to ${ARTIFACTORY_FE_GENERIC}",
                            tokenCredentialId: 'slack-global-integration-token')
                }
            }
        }
        fixed {
            slackSend(channel: 'fe-drift',
                    color: 'good',
                    message: "${env.JOB_NAME} #${env.BUILD_NUMBER} back to normal: ${env.BUILD_URL}",
                    tokenCredentialId: 'slack-global-integration-token')

        }
    }
}
